basePath: /
definitions:
  target:
    properties:
      address_1: {type: string}
      address_2: {type: string}
      address_3: {type: string}
      address_4: {type: string}
      address_5: {type: string}
      address_6: {type: string}
      country: {type: string}
      country_of_birth: {type: string}
      dob: {type: string}
      group_id: {type: string}
      group_type: {type: string}
      last_updated: {type: string}
      listed_on: {type: string}
      nationality: {type: string}
      nin: {type: string}
      passport: {type: string}
      position: {type: string}
      postcode: {type: string}
      regime: {type: string}
      title: {type: string}
      first_name: {type: string}
      last_name: {type: string}
      second_name: {type: string}
      third_name: {type: string}
      fourth_name: {type: string}
      fifth_name: {type: string}
      other_info: {type: string}
      town_of_birth: {type: string}
    type: object
host: 10.244.115.98:5000
version: 0.0.1
info:
  contact: {email: elmurci@gmail.com, name: Javi Romero}
  description: Query the Consolidated list of targets from the UK Government (https://www.gov.uk/government/publications/financial-sanctions-consolidated-list-of-targets/consolidated-list-of-targets)
  title: AML Service
  x-21-category: utilities
  x-21-github-project-url: https://github.com/elmurci/aml-service
  x-21-keywords: [aml, anti money laundering]
  x-21-app-image: https://cdn.filepicker.io/api/file/too33igBTduTP5jwQiSl
  x-21-quick-buy: "$ 21 buy url http://10.244.115.98:5000/aml?dob=05/02/1981\n\n# Filters (at least one): \n\n #
  
  first_name=Peter&last_name=Jones&nationality=Afghan&group_type=Individual&dob=05/02/1981

  \n\n#        \
  Output:\n\n\
    # 
    {
    \"data\": [\n#        \
        {
            \"address_1\": \"\",\n#        \
            \"address_2\": \"\",\n#        \
            \"address_3\": \"\",\n#        \
            \"address_4\": \"\",\n#        \
            \"address_5\": \"\",\n#        \
            \"address_6\": \"\",\n#        \
            \"alias_type\": \"Prime Alias\",\n#        \
            \"country\": \"\",\n#        \
            \"country_of_birth\": \"\",\n#        \
            \"dob\": \"05/02/1981\",\n#        \
            \"fifth_name\": \"\",\n#        \
            \"first_name\": \"Said Jan\",\n#        \
            \"fourth_name\": \"\",\n#        \
            \"group_id\": \"11634\",\n#        \
            \"group_type\": \"Individual\",\n#        \
            \"last_name\": \"'ABD AL-SALAM\",\n#        \
            \"last_updated\": \"28/02/2011\",\n#        \
            \"listed_on\": \"28/02/2011\",\n#        \
            \"nationality\": \"Afghan\",\n#        \
            \"nin\": \"281020505755  (Kuwaiti Civil ID no) under name Said Jan 'Abd al-Salam\",\n#        \
            \"other_info\": \"UN Ref QI.A.289.11. In approximately 2005, ran a 'basic training' camp for Al-Qaida in Pakistan. Also referred to as Said Jhan and Nangiali.\",\n#        \
            \"passport\": \"(1) OR801168 (Afghan). Issued on 28 Feb 2006. Expires 27 Feb 2011 under name Said Jan 'Abd al-Salam (2) 4117921 (Pakistani). Issued on 9 Sept 2008. Expires 9 Sept 2013 under name Dilawar Khan Zain Khan (DOB 1 Jan 1972)\",\n#        \
            \"position\": \"\",\n#        \
            \"postcode\": \"\",\n#        \
            \"regime\": \"The ISIL (Da'esh) and Al-Qaida organisations\",\n#        \
            \"second_name\": \"\",\n#        \
            \"third_name\": \"\",\n#        \
            \"title\": \"\",\n#        \
            \"town_of_birth\": \"\"\n#        \
        }\n#        \
    ],\n#        \
    \"status\": \"ok\"
  }"
  x-21-total-price: {max: 1000, min: 1000}
paths:
  /aml:
    get:
      consumes: [application/json]
      produces: [application/json]
      responses:
        200:
          description: List of targets found
          schema:
            properties:
              data:
                items: {$ref: '#/definitions/target'}
                type: array
            type: object
      summary: Search the list of targets from the Government database.
  /client:
    get:
      consumes: [application/json]
      produces: [application/json]
      responses:
        200:
          description: Client
          schema:
            properties:
              data:
                items: {$ref: '#/definitions/target'}
                type: array
            type: object
      summary: Client to search the list of targets from the Government database.
schemes: [http]
swagger: '2.0'
x-21-manifest-path: /manifest